##Gradio Examples:
single_examples = [[
                    False,
                    "no clause",
                    "No attempt was made. The engagement letter names the individual and the client requires that person to attend each shift.",
                    "unspecified",
                    "The depot supervisor allocates tasks at the start of each shift and reassigns the worker between stations during the day.",
                    "The worker follows the client's written operating procedures and is corrected on the spot where the method departs from them.",
                    "Shifts are 07:00 to 15:30 on a rota published by the client, worked entirely at the client's warehouse.",
                    "The worker reports to the shift supervisor, signs in on the depot system, and reports absence to that supervisor before the shift begins.",
                    1,
                    False,
                    False,
                    False,
                    "Errors are corrected during paid hours at the client's cost. The worker bears no expense for remedial work.",
                    "There is no realistic prospect of a loss. The worker is paid hourly and supplies nothing beyond personal safety boots.",
                    "client",
                    "The worker wears the client's branded uniform, holds a staff access badge, and is introduced to visiting drivers as a member of the depot team.",
                    "The worker completes the client's induction and manual-handling training, attends daily briefings, and is supervised continuously.",
                    26,
                    3,
                    True,
                    "The full-time rota leaves no practical capacity for other work, and the contract requires written consent before accepting any.",
                    "time",
                ],
                [
                    True,
                    "yes",
                    "The worker asked to send an assistant for one week in March. The client declined without giving a reason and the worker attended personally. The clause has not been used since.",
                    "worker",
                    "The client issues a weekly assignment list and sets the order where deadlines collide. The worker arranges the detailed sequence of interviews and desk research.",
                    "The worker selects the research method and drafts independently, though the client's project lead reviews methodology at checkpoints and can require changes to the reporting format.",
                    "The agreement states a target of 24 hours per week, chosen by the worker within agreed availability windows. Most work is remote with one client-site meeting each fortnight.",
                    "The worker reports deliverables to a project lead and attends fortnightly reviews. There is no disciplinary chain, though missed deadlines escalate to the account director.",
                    3,
                    True,
                    True,
                    False,
                    "The worker revises reports containing avoidable errors at no extra charge. Revisions caused by a changed brief are quoted separately.",
                    "Payment is partly by milestone, so extensive rework reduces the return on the worker's time. Business costs are modest and no specialist equipment is required.",
                    "mixed",
                    "The worker appears on project materials as an external research consultant and keeps a separate email signature, but has access to the client's collaboration platform and is listed in its project directory.",
                    "The client provides a systems induction and reviews deliverables. No employee benefits are given and supervision is limited to project coordination.",
                    11,
                    3,
                    False,
                    "Other engagements are permitted, though the weekly availability commitment limits overlapping deadlines. Two small projects for other clients were completed in the period.",
                    "both",
                ]]
